name: CI

on:
  push:
    branches:
    - "*"

  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: setup node
      uses: actions/setup-node@v3 
    - name: run npm ci
      run: npm ci
    - name: run npx playwright install
      run: npx playwright install-deps
    - name: run npx playwright test
      run: xvfb-run --auto-servernum -- npm run test
    - name: upload playwright test report
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report
        retention-days: 30
    - name: deploy to github pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: playwright-report
